name: CodeFormer_stage3_custom
model_type: CodeFormerJointModel
num_gpu: 0
manual_seed: 0
datasets:
  train:
    name: CustomDataset
    type: FFHQBlindJointDataset
    dataroot_gt: datasets/ffhq/ffhq_512
    filename_tmpl: '{}'
    io_backend:
      type: disk
    in_size: 512
    gt_size: 512
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
    use_hflip: true
    use_corrupt: true
    blur_kernel_size: 41
    use_motion_kernel: true
    motion_kernel_prob: 0.05
    kernel_list:
    - iso
    - aniso
    kernel_prob:
    - 0.5
    - 0.5
    blur_sigma:
    - 0.1
    - 10.0
    downsample_range:
    - 1.0
    - 12.0
    noise_range:
    - 0.0
    - 20.0
    jpeg_range:
    - 50
    - 100
    blur_sigma_large:
    - 1.0
    - 15.0
    downsample_range_large:
    - 4.0
    - 30.0
    noise_range_large:
    - 0.0
    - 30.0
    jpeg_range_large:
    - 30
    - 80
    latent_gt_path: null
    num_worker_per_gpu: 0
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu
network_g:
  type: CodeFormer
  dim_embd: 512
  n_head: 8
  n_layers: 9
  codebook_size: 1024
  connect_list:
  - '32'
  - '64'
  - '128'
  - '256'
  fix_modules:
  - quantize
  - generator
network_vqgan:
  type: VQAutoEncoder
  img_size: 512
  nf: 64
  ch_mult:
  - 1
  - 2
  - 2
  - 4
  - 4
  - 8
  quantizer: nearest
  codebook_size: 1024
network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64
  n_layers: 4
path:
  pretrain_network_g: null
  param_key_g: params_ema
  strict_load_g: false
  pretrain_network_d: null
  resume_state: D:\.gemini-scratch\custom-ai-enhancer\models\CodeFormer\experiments\20260708_201102_CodeFormer_stage3_custom\training_states\1600.state
train:
  use_hq_feat_loss: true
  feat_loss_weight: 1.0
  cross_entropy_loss: true
  entropy_loss_weight: 0.5
  scale_adaptive_gan_weight: 0.1
  optim_g:
    type: Adam
    lr: 5.0e-05
    weight_decay: 0
    betas:
    - 0.9
    - 0.99
  optim_d:
    type: Adam
    lr: 5.0e-05
    weight_decay: 0
    betas:
    - 0.9
    - 0.99
  scheduler:
    type: CosineAnnealingRestartLR
    periods:
    - 150000
    restart_weights:
    - 1
    eta_min: 2.0e-05
  total_iter: 20000
  warmup_iter: -1
  ema_decay: 0.997
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true
  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: 1.0
  use_adaptive_weight: true
  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 0
  manual_seed: 0
val:
  val_freq: 500
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
logger:
  print_freq: 1
  save_checkpoint_freq: 50
  use_tb_logger: false
  wandb:
    project: null
find_unused_parameters: true
dist_params: null
dist: false
